# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e42aeb83e2471516500e0793d06b1b649a661f7e8608dbce3d2e023c8d37b7562a70bcdd311540aab34aa6f380fa5176c582ae6a627a9df83925be9d1abb67b6

test:
  secret_key_base: ab157b418c10aa0fc0d91784255da02e32501783ade092b5bd2336e34078591bdb25f445d16b74295c7a79bae972c38c078b3d0b12cfa4c6576cd35f286b31ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
